test: off

branches:
  except:
  - /travis/

environment:
  APPVEYOR_BUILD_WORKER_IMAGE: Visual Studio 2017
  GYP_MSVS_VERSION: 2017
  PDFium_BRANCH: chromium/3538

configuration:
  - Release
  - Debug

platform:
  - x86
  - x64

build_script:
  - call build.bat
  - cd %APPVEYOR_BUILD_FOLDER%
  - call test.bat

artifacts:
  - path: pdfium-*.zip
    name: PDFium library

